have_fun: true

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 10
  pull_request_opened:
    help: false
    summary: true
    code_review: true

ignore_patterns:
  - "public/**"
  - "**/*.json"
  - "**/*.svg"
  - "**/*.css"
  - "**/*.d.ts"
  - "package.json"
  - "package-lock.json"
  - "vite.config.ts"
  - "tsconfig.json"
  - "index.html"