have_fun: true

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 10
  pull_request_opened:
    help: false
    summary: true
    code_review: true

ignore_patterns:
  - "public/**"
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> e5b2f46 (fix: ignore_patternsをglob形式に修正)
  - "**/*.json"
  - "**/*.svg"
  - "**/*.css"
  - "**/*.d.ts"
  - "package.json"
  - "package-lock.json"
<<<<<<< HEAD
=======
  - "*.json"
  - "*.svg"
  - "*.css"
  - "*.d.ts"
  - "package*.json"
>>>>>>> d8a428e (fix: Geminiの設定ファイルを修正（最小構成＋スタイル対応）)
=======
>>>>>>> e5b2f46 (fix: ignore_patternsをglob形式に修正)
  - "vite.config.ts"
  - "tsconfig.json"
  - "index.html"